Update contracts and add liquidity-helper (#1)
* Update to mainnet versions

* Fix tests to work with pact 4.4

* wrapper: Fix unbounded gas growth in remove-liquidity

* exchange/wrapper: Do not use try for division

* Initial version of liquidity-helper

* liquidity-helper: fix add-liquidity order

* Finalize liquidity-helper

Update coin contract, add more tests

* Restore mainnet version of wrapper.pact

Functions will be removed at a later date

* Update Pact version in CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,7 +17,7 @@ jobs:
   # This workflow contains a single job called "build"
   test-pact:
     # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -28,16 +28,15 @@ jobs:
         run: |
           mkdir bin
           cd bin
-          wget https://github.com/kadena-io/pact/releases/download/v4.3/pact-4.3-linux-18.04.zip
+          wget https://github.com/kadena-io/pact/releases/download/v4.4.1/pact-4.4.1-linux-20.04.zip
           unzip "pact*.zip"
           chmod +x pact
           cd ..
-      - name: Install z3 (ubuntu-18.04)
-        uses: pavpanchekha/setup-z3@0.2.0
-        with:
-          version: "4.8.10"
-          architecture: "x64"
-          distribution: "ubuntu-18.04"
+
+      - name: Install z3 (ubuntu-20.04)
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y z3
 
       - name: wrapper/init.repl
         run: |
@@ -63,6 +62,13 @@ jobs:
       - name: kadenaswap/oracle.repl
         run: |
           bin/pact -t kadenaswap/oracle.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+
+      - name: kadenaswap/gas-station/gas-station.repl
+        run: |
+          bin/pact -t kadenaswap/gas-station/gas-station.repl > out.log 2>&1
           cat out.log
           r=`tail -1 out.log | grep "Load successful"`
           if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
